allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    compileSdkVersion = 34
    targetSdkVersion = 34
    minSdkVersion = 23
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    project.plugins.withId("com.android.application") {
        project.plugins.apply("org.jetbrains.kotlin.android")
    }

    project.plugins.withId("com.android.library") {
        project.android {
            compileSdk 34
        }
        project.plugins.apply("org.jetbrains.kotlin.android")
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
