- name: Install Android SDK 34
  run: |
    yes | "$ANDROID_SDK_ROOT"/cmdline-tools/latest/bin/sdkmanager --licenses
    yes | "$ANDROID_SDK_ROOT"/cmdline-tools/latest/bin/sdkmanager \
      "platforms;android-34" \
      "build-tools;34.0.0" \
      "platform-tools" \
      "ndk;28.2.13676358"
